%% trialDataPath.m
% adds everything to the path that I'll need to make, load, and work with
% trial data structures. I'm doing it this way so we don't have file
% permission issues with the shared computers.

% these path names will only be right if we're on GOB, so I guess we'll
% have to make a couple different versions
switch getenv('ComputerName')
    case 'GOB'
        addpath('C:\Users\klb807\Documents\git\TrialData\Analysis',...
            'C:\Users\klb807\Documents\git\TrialData\DataProcessing',...
            'C:\Users\klb807\Documents\git\TrialData\Plotting',...
            'C:\Users\klb807\Documents\git\TrialData\Tools',...
            'C:\Users\klb807\Documents\git\TrialData\util',...
            'C:\Users\klb807\Documents\git\proc-kevin\Helpful_Functions',...
            'C:\Users\klb807\Documents\git\proc-kevin\Helpful_Functions\pathSetup',...
            'C:\Users\klb807\Documents\git\loadTDfromCDS');

        disp('TrialData related directories added to path');
    otherwise
        disp('Paths have not been added for computers besides GOB.')
end