%%
[fn,pn] = uigetfile('*.nev');

tempfilename = split(fn,'.nev');
tempfilename = tempfilename{1};
signal_info = {
    initSignalStruct('filename', [pn,filesep,fn],...
        'routine', @processNEV,...
        'params',struct(),...
        'name',{'rightM1','trial_table'},...
        'type',{'spikes','event'},...
        'label','');

    
    initSignalStruct('filename',[pn,filesep,tempfilename,'.ns3'],...
        'routine',@processNSx,...
        'params',struct(),...
        'name',{'EMG_FDSr','EMG_FDSu','EMG_FDPr','EMG_FDPu','EMG_FCR1','EMG_ECU1','EMG_ECU2','EMG_ECR1','EMG_ECR2','EMG_EPL','EMG_EDC2','EMG_FCU1'},...
        'label',{'EMG_FDSr','EMG_FDSu','EMG_FDPr','EMG_FDPu','EMG_FCR1','EMG_ECU1','EMG_ECU2','EMG_ECR1','EMG_ECR2','EMG_EPL','EMG_EDC2','EMG_FCU1'},...
    	'type','EMG');

    initSignalStruct('filename',[pn,filesep,tempfilename,'.ns2'],...
        'routine',@processNSx,...
        'params',struct(),...
        'name','Force_AirDevice',...
        'label','',...
        'type','generic');



};


%%

[TD,td_params,flag] = convertDataToTD(signal_info);



